# Generated by Django 5.2.7 on 2025-10-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='driver',
            field=models.CharField(default='bridge', max_length=20),
        ),
        migrations.AddField(
            model_name='network',
            name='subnet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='network',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pod',
            name='status',
            field=models.CharField(default='created', max_length=20),
        ),
    ]
