# Generated by Django 5.2.7 on 2025-10-31 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0002_network_driver_network_subnet_network_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pods', to='netbox_containers.network'),
        ),
    ]
