# Generated by Django 5.2.7 on 2025-10-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0003_pod_network'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pod',
            name='network',
        ),
        migrations.AddField(
            model_name='pod',
            name='networks',
            field=models.ManyToManyField(blank=True, null=True, related_name='pods', to='netbox_containers.network'),
        ),
    ]
