# Generated by Django 5.2.7 on 2025-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_containers', '0004_remove_pod_network_pod_networks'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ('name', 'pk')},
        ),
        migrations.AlterModelOptions(
            name='pod',
            options={'ordering': ('name', 'pk')},
        ),
        migrations.AddField(
            model_name='network',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='container_networks', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='network',
            name='virtual_machines',
            field=models.ManyToManyField(blank=True, related_name='container_networks', to='virtualization.virtualmachine'),
        ),
    ]
