# Generated by Django 5.2.7 on 2025-11-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0082_add_prefix_network_containment_indexes'),
        ('netbox_containers', '0005_alter_network_options_alter_pod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='prefixes',
            field=models.ManyToManyField(blank=True, related_name='container_networks', to='ipam.prefix'),
        ),
        migrations.AddField(
            model_name='network',
            name='subnets_text',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
