# Generated by Django 5.2.7 on 2025-11-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0006_network_prefixes_network_subnets_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='subnet',
        ),
    ]
