# Generated by Django 5.2.7 on 2025-11-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0007_remove_network_subnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
