# Generated by Django 5.2.7 on 2025-11-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0008_network_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
