# Generated by Django 5.2.7 on 2025-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0009_alter_network_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
