# Generated by Django 5.2.7 on 2025-11-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0010_network_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pod',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
