# Generated by Django 5.2.7 on 2025-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0011_network_comments_pod_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='driver',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pod',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
