# Generated by Django 5.2.7 on 2025-11-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('netbox_containers', '0012_alter_network_driver_alter_pod_status'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pod',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='container_pods', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='pod',
            name='virtual_machines',
            field=models.ManyToManyField(blank=True, related_name='container_pods', to='virtualization.virtualmachine'),
        ),
    ]
