# Generated by Django 5.2.7 on 2025-11-02 16:34

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_containers', '0013_pod_devices_pod_virtual_machines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('registry', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Registry must be a hostname (optionally with port). Example: registry-1.docker.io or quay.io', regex='^[a-z0-9][a-z0-9.-]*(:\\d+)?$')])),
                ('name', models.CharField(max_length=255)),
                ('default_tag', models.CharField(blank=True, default='latest', max_length=128)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('registry', 'name', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('image_tag', models.CharField(blank=True, default='latest', max_length=128)),
                ('os', models.CharField(blank=True, max_length=32)),
                ('arch', models.CharField(blank=True, max_length=32)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_tags', to='netbox_containers.image')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Image Tag',
                'verbose_name_plural': 'Image Tags',
                'ordering': ('image__registry', 'image__name', 'image_tag', 'arch', 'os', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('registry', 'name'), name='uniq_image_registry_name'),
        ),
        migrations.AddConstraint(
            model_name='imagetag',
            constraint=models.UniqueConstraint(fields=('image', 'image_tag', 'os', 'arch'), name='uniq_imagetag_variants_per_image'),
        ),
    ]
