# Generated by Django 5.2.7 on 2026-01-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0014_image_imagetag_image_uniq_image_registry_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagetag',
            options={'ordering': ('image__registry', 'image__name', 'image_tag', 'arch', 'os', 'digest', 'size', 'pk')},
        ),
        migrations.AddField(
            model_name='imagetag',
            name='digest',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='imagetag',
            name='size',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
