# Generated by Django 5.2.7 on 2026-01-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0015_alter_imagetag_options_imagetag_digest_imagetag_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetag',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
