# Generated by Django 5.2.7 on 2026-01-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0016_imagetag_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetag',
            name='digest',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='imagetag',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
