# Generated by Django 5.2.7 on 2026-01-02 20:10

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0215_rackreservation_status'),
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_containers', '0018_volume'),
        ('virtualization', '0048_populate_mac_addresses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('published_ports', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.TextField(blank=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='container_containers', to='dcim.device')),
                ('networks', models.ManyToManyField(blank=True, null=True, related_name='containers', to='netbox_containers.network')),
                ('pods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='netbox_containers.pod')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('virtual_machines', models.ManyToManyField(blank=True, related_name='container_containers', to='virtualization.virtualmachine')),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ('name', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
