# Generated by Django 5.2.7 on 2026-01-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0019_container'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='pods',
            new_name='pod',
        ),
    ]
