# Generated by Django 5.2.7 on 2026-01-02 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0020_rename_pods_container_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='image_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='netbox_containers.imagetag'),
        ),
    ]
