# Generated by Django 5.2.7 on 2026-01-03 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0021_container_image_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='add_host',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='container',
            name='command',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='cpu_limit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='environment',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='container',
            name='memory_limit',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a positive number optionally followed by b, k, m, or g (e.g. 512m, 1g, 1048576).', regex='^[1-9]\\d*(?:[bBkKmMgG])?$')]),
        ),
        migrations.AddField(
            model_name='container',
            name='user_namespaces',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='container',
            name='volumes',
            field=models.ManyToManyField(blank=True, null=True, related_name='containers', to='netbox_containers.volume'),
        ),
    ]
