# Generated by Django 5.2.7 on 2026-01-04 18:35

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_containers', '0022_container_add_host_container_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='volumes',
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('mount_type', models.CharField(default='volume', max_length=16)),
                ('host_path', models.CharField(blank=True, max_length=512)),
                ('dest_path', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator(message='Destination path must be an absolute path inside the container (e.g. /var/lib/pgsql/data).', regex='^/.*')])),
                ('options', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Options must be a comma-separated list (e.g. ro,Z,rshared,uid=1000).', regex='^[A-Za-z0-9=,_:+.\\-]*$')])),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='netbox_containers.container')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mounts', to='netbox_containers.volume')),
            ],
            options={
                'verbose_name': 'Mount',
                'verbose_name_plural': 'Mounts',
                'ordering': ('container_id', 'pk'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
