# Generated by Django 5.2.7 on 2026-02-03 18:32

import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0133_make_cf_minmax_decimal'),
        ('netbox_containers', '0027_remove_networks_from_container_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkattachment',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='networkattachment',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
