# Generated by Django 5.2.7 on 2026-02-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0028_networkattachment_custom_field_data_and_more'),
        ('netbox_containers', '0028_secret'),
    ]

    operations = [
    ]
