# Generated by Django 5.2.7 on 2026-02-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0029_secret_options_text'),
        ('netbox_containers', '0030_secret_custom_field_data_secret_tags'),
    ]

    operations = [
    ]
