# Generated by Django 5.2.7 on 2026-02-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0030_container_secret'),
        ('netbox_containers', '0031_merge_20260203_1937'),
    ]

    operations = [
    ]
