# Generated by Django 5.2.7 on 2026-02-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0031_published_ports_text'),
        ('netbox_containers', '0033_containersecret_custom_field_data_and_more'),
    ]

    operations = [
    ]
