# Generated by Django 5.2.7 on 2026-02-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_containers', '0032_pod_add_host'),
        ('netbox_containers', '0034_merge_20260203_2030'),
    ]

    operations = [
    ]
