name: Bug report
description: Report a reproducible problem in the plugin
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce it.
  - type: input
    id: netbox_version
    attributes:
      label: NetBox version
      placeholder: "e.g. 4.4.3"
    validations:
      required: true
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version or commit
      placeholder: "e.g. 0.1.0 or commit hash"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Traceback or logs
      description: Paste full traceback/log output if available.
      render: shell
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false

