name: Feature request
description: Suggest an improvement for the plugin
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please describe the use case and expected result.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe how you think this should work.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: NetBox/UI/API impact
      description: Mention model, migration, API, or UI implications if known.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
    validations:
      required: false

