name: Python Code Validation

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint and Validate Python Code
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python and tools
        run: |
          dnf -y install python3 python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade flake8
          python3 -m pip install --upgrade pylint

      - name: Check syntax validity
        run: |
          echo "Checking Python syntax..."
          python -m compileall .

      - name: Run flake8 (PEP8 style guide)
        run: |
          echo "Running flake8 for PEP8 compliance..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Run pylint
        run: |
          echo "Running pylint..."
          pylint $(find . -name "*.py")